### ISSUE TITLE
Crash after installing in new virtualenv

### ISSUE THREAD

**Issue by FastGeert** [grimpy/ovcli#4]
```python
Traceback (most recent call last):
  File "/home/geert/envs/ovc/bin/ovcsh", line 6, in <module>
    from ovcli.shell import main
  File "/home/geert/envs/ovc/lib/python3.6/site-packages/ovcli/shell.py", line 7, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

**Comment by FastGeert** [comment]
I discovered that the toolkit also need the following packages:
- nose
- nose-parameterized
